stages:
  - build
  - test
  - deploy

variables:
  NODE_VERSION: "14"

build:
  stage: build
  image: node:${NODE_VERSION}
  script:
    - npm ci
    - npm run build
  artifacts:
    paths:
      - dist/

lint:
  stage: test
  image: node:${NODE_VERSION}
  script:
    - npm ci
    - npm run lint

unit-test:
  stage: test
  image: node:${NODE_VERSION}
  script:
    - npm ci
    - npm run test:unit

integration-test:
  stage: test
  image: node:${NODE_VERSION}
  script:
    - npm ci
    - npm run test:integration

deploy:
  stage: deploy
  image: node:${NODE_VERSION}
  script:
    - echo "Deploying to production"
    # Add your deployment steps here
  only:
    - main
